### ISSUE TITLE
decodeCheck().value returned 16 decimal places instead 18

### ISSUE THREAD

**Issue by MiGiN** [MinterTeam/minter-js-sdk#16]
const decodeCheck = require('minter-js-sdk').decodeCheck
raw_check = '+KeGMTIzMTIzAYQ7msn/ik1OVAAAAAAAAACID5YgzypL6VW4Qf02WUSNwWoRy/I+nbgYsCgnD3GYTh4qw9DwG5Jo0hnGNHZihzp34OH19er6+SVN8pmmKglnqqMl8jd0+CEp/D0BG6CEcBI3I8L5sOzMekXmoQuJwb2tPU50qCZjYzLkNW4KdqBYG1BxTlSme94djuB1HvnfUk+Zjiur2JU8dvnxZyBNxw=='
check = Buffer.from(raw_check, 'base64')
decodeCheck(check).value === '1.123121231215454549'
// returned false

**Comment by shrpne** [comment]
Thank you for the issue!

Actually your code returns `1.1231212312154546`

And this check contains this much PIP: `1123121231215454600`
Which is `1.123121231215454600` MNT
`1.123121231215454600` === `1.1231212312154546`

So it just discards insignificant zeros.
If you need fixed-length decimal, just pad it with zeros.

**Comment by shrpne** [comment]
precision loss fixed in the v0.28.0 981a8e32b1611ff5c1b65ae638c4053f08d98f4a
