### ISSUE TITLE
wrong chain id

### ISSUE THREAD

**Issue by QuietAko** [MinterTeam/minter-js-sdk#26]
const minter = new Minter({apiType: 'node', baseURL: 'https://node-api.testnet.minter.network/v2/'});
const txParams = {
    nonce: 1,
    chainId: 1,
    type: TX_TYPE.SEND,
    data: {
        to: 'Mx24a8f1c0a2f2b0545b0b87b9fcce3f3a6059c44d',
        value: 10,
        coin: 0, // BIP id
    },
    gasCoin: 0, // BIP id
    gasPrice: 1,
    payload: 'custom message',
};

minter.postTx(txParams, {privateKey: ""})
    .then((txHash) => {
        alert(`Tx created: ${txHash}`);
    }).catch((error) => {
        const errorMessage = error.response.data.error.message
        console.log(error);
    });

**Comment by shrpne** [comment]
Hi! You are trying to send mainnet tx (chainId: 1) to testnet node.

Use chainId: 2 instead
