### ISSUE TITLE
Wrong chain id

### ISSUE THREAD

**Issue by DevAza** [MinterTeam/minter-js-sdk#3]
const minterSDK = new Minter({apiType: 'gate', baseURL: 'https://gate.minter.network'});
const txParams = new SendTxParams({
    privateKey: '***',
    nonce: 1,
    chainId: 0x1,
    address: '***',
    amount: 10,
    coinSymbol: 'BIP',
    feeCoinSymbol: 'BIP',
    gasPrice: 1,
    message: 'custom message',
});

minterSDK.postTx(txParams)
    .then((txHash) => {
        console.log(`Tx created: ${txHash}`);
    })
    .catch((error) => {
        var errorMessage = error.response.data.error.log;
        //console.log(error);
        console.log(errorMessage);
    });

When you try to send a transaction, the following error occurs:
Wrong chain id

Help me please

**Comment by shrpne** [comment]
gate.minter.network is the testnet version (chainId: 2).
you can use gate-api.minter.network for  mainnet

**Comment by DevAza** [comment]
Thanks
