### ISSUE TITLE
.estimateTxCommission() return Cannot read property 'tx' of undefined

### ISSUE THREAD

**Issue by DevAza** [MinterTeam/minter-js-sdk#4]
https://github.com/MinterTeam/minter-js-sdk#estimatetxcommission

Return error:
    if (!params.tx && !params.transaction) {
                ^
TypeError: Cannot read property 'tx' of undefined
    at _default.estimateCoinBuy [as estimateTxCommission] (/var/www/developer/data/www/bipstore.ru/libs/nodejs/node_modules/minter-js-sdk/dist/cjs/api/estimate-tx-commission.js:27:17)
    at Object.<anonymous> (/var/www/developer/data/www/bipstore.ru/libs/nodejs/sendBipTest.js:18:11)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

My code is:
var Minter = require('minter-js-sdk').Minter,
    SendTxParams = require('minter-js-sdk').SendTxParams,
    MinterUtil = require('minterjs-util'),
    MinterTx = require('minterjs-tx'),
    fee = MinterUtil.getFeeValue(MinterTx.TX_TYPE_SEND);

const minterSDK = new Minter({apiType: 'gate', baseURL: 'https://gate-api.minter.network'});
var txParams = new SendTxParams({
    privateKey: '***',
    chainId: 0x1,
    address: '****',
    amount: 100,
    coinSymbol: 'BIP',
    feeCoinSymbol: 'BIP',
    message: 'custom message',
});

minterSDK.estimateTxCommission()
    .then((commission) => {
        console.log(commission);
        // 0.1
    })
    .catch((error) => {
        // ...
        console.log(error)
    })

**Comment by DevAza** [comment]
How can I find out the commission before sending a transaction to deduct it from the amount sent?
Help me please

**Comment by DevAza** [comment]
Or how to set your commission? If you send gasPrice = 0.01 to the SendTxParams class, then the commission is high:
Insufficient funds for sender account: ***. Wanted 163208849.6860000117 bip.

**Comment by DevAza** [comment]
And for some reason, the commission when sending 0.038, when MinterUtil.getFeeValue (MinterTx.TX_TYPE_SEND) returns 0.01

**Comment by DevAza** [comment]
Big commission because of
message: 'custom message',

**Comment by shrpne** [comment]
Sorry, there was a mistake in the docs, you should pass tx hex string as parameter:
```
minterSDK.estimateTxCommission({
     transcation: 'f8920101028a4d4e540000000000000001aae98a4d4e...'
})
```

Also base coin fee can be estimated offline, you can use this method:
https://github.com/MinterTeam/minterjs-util/blob/master/src/fee.js#L5

You can read how comission is calculated in the docs:
https://docs.minter.network/#section/Commissions

Also you should know, that `gasPrice` is an integer multiplier, that applied to comission to bypass mempool's minimum gas price. Minimum gas price is a mechanism to reduce tx count in the block during a high load.
