### ISSUE TITLE
Ubuntu npm install

### ISSUE THREAD

**Issue by BipBipov** [MinterTeam/minter-js-sdk#9]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/shrpne/elliptic.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by shrpne** [comment]
please update to the latest version
